### ISSUE TITLE
Tache ant pour properties liquibase

### ISSUE THREAD

**Issue by noemienicolas** [DSI-Ville-Noumea/liquibase-archetype#1]
Dans mes projets liquibase, j'ai également pour habitude d'avoir une tache ANT qui me permet de mettre les bonnes infos ( Dev,intégration...) dans le fichier liquibase.properties.
Serait-il possible d'avoir cette fonctionnalité dès la génération de l'archetype ? ;-)
Merci bien à vous l'equipe "archetype" !

**Comment by mbarre** [comment]
:+1:
